### ISSUE TITLE
Set speed once at beginning of phase instead of every update

### ISSUE THREAD

**Issue by propstg** [Jasonleh99/PlateupPrepGhost#10]
Would it be possible to only set the speed once at the beginning of a phase? I know there are systems that only fire at the beginning of certain phases, but I don't know how difficult they'd be to incorporate into the harmony patching.

The reason I'm asking is that this mod is setting the speed after every player update, which breaks my DashPing mod's ability to temporarily alter the player's speed, because the speed gets overridden immediately in the postfix after changing it.

**Comment by Jasonleh99** [comment]
Ayo, took a look at this

I fixed it with the https://github.com/Jasonleh99/PlateupPrepGhost/releases/tag/1.21 update.

**NOTE**
**This is not full compatibility**
The speed will not be reset to the PrepGhost setting after dashing until the next game phase or update to the PrepGhost settings. This is because the dash mod returns the player to the default speed after the dash is complete:
![image](https://user-images.githubusercontent.com/36774043/215365927-cf36d88f-3911-4e58-a61e-1005ca501501.png)

**Comment by propstg** [comment]
Awesome, thank you!
